def help(console):
    console.print("[bold red]Correct usage:[/bold red]")
    console.print("[red]python3 main.py[/red] \[udp/tcp/http] \[time] \[threads] \[IP/URL]")
    console.print("")
    console.print("[bold yellow]Method:[/bold yellow]")
    console.print("udp - Attack using UDP packets")
    console.print("tcp - Attack using TCP packets")
    console.print("http - Attack using HTTP packets")
    console.print("")
    console.print("[bold yellow]IP Address:[/bold yellow]")
    console.print("for udp and tcp insert the server IP address")
    console.print("for http insert the website URL")
    console.print("")
    console.print("[bold yellow]Time:[/bold yellow]")
    console.print("Enter how long the attack should last")
    console.print("")
    console.print("[bold yellow]Threads:[/bold yellow]")
    console.print("Enter how many subprocesses the program must generate to attack the victim (more subprocesses = more power)")

    console.print("")